[
  {
    state: "Karnataka",
    district: "Bangalore",
    market: "Ramanagara",
    commodity: "Bhindi(Ladies Finger)",
    variety: "Bhindi",
    grade: "FAQ",
    arrival_date: "29/10/2024",
    min_price: "4000",
    max_price: "5000",
    modal_price: "4600",
    icon: "\ud83d\udce6",
  },
  {
    state: "Karnataka",
    district: "Bangalore",
    market: "Ramanagara",
    commodity: "Cabbage",
    variety: "Cabbage",
    grade: "FAQ",
    arrival_date: "29/10/2024",
    min_price: "1200",
    max_price: "1600",
    modal_price: "1400",
    icon: "\ud83e\udd6c",
  },
  {
    state: "Karnataka",
    district: "Bangalore",
    market: "Ramanagara",
    commodity: "Cauliflower",
    variety: "Cauliflower",
    grade: "FAQ",
    arrival_date: "29/10/2024",
    min_price: "3000",
    max_price: "4000",
    modal_price: "3600",
    icon: "\ud83e\udd66",
  },
  {
    state: "Karnataka",
    district: "Bangalore",
    market: "Ramanagara",
    commodity: "Chilly Capsicum",
    variety: "Chilly Capsicum",
    grade: "FAQ",
    arrival_date: "29/10/2024",
    min_price: "4000",
    max_price: "4800",
    modal_price: "4400",
    icon: "\ud83d\udce6",
  },
  {
    state: "Karnataka",
    district: "Bangalore",
    market: "Ramanagara",
    commodity: "Green Chilli",
    variety: "Green Chilly",
    grade: "FAQ",
    arrival_date: "29/10/2024",
    min_price: "3000",
    max_price: "5000",
    modal_price: "4000",
    icon: "\ud83c\udf36\ufe0f",
  },
  {
    state: "Karnataka",
    district: "Bangalore",
    market: "Ramanagara",
    commodity: "Raddish",
    variety: "Raddish",
    grade: "FAQ",
    arrival_date: "29/10/2024",
    min_price: "3000",
    max_price: "5000",
    modal_price: "4000",
    icon: "\ud83d\udce6",
  },
  {
    state: "Karnataka",
    district: "Bangalore",
    market: "Ramanagara",
    commodity: "Seemebadnekai",
    variety: "Seemebadanekai",
    grade: "FAQ",
    arrival_date: "29/10/2024",
    min_price: "1600",
    max_price: "2200",
    modal_price: "2000",
    icon: "\ud83d\udce6",
  },
  {
    state: "Karnataka",
    district: "Bangalore",
    market: "Ramanagara",
    commodity: "Snakeguard",
    variety: "Snakeguard",
    grade: "FAQ",
    arrival_date: "29/10/2024",
    min_price: "3000",
    max_price: "4000",
    modal_price: "3600",
    icon: "\ud83d\udce6",
  },
  {
    state: "Karnataka",
    district: "Chamrajnagar",
    market: "Chamaraj Nagar",
    commodity: "Brinjal",
    variety: "Other",
    grade: "FAQ",
    arrival_date: "29/10/2024",
    min_price: "1000",
    max_price: "1600",
    modal_price: "1300",
    icon: "\ud83c\udf46",
  },
  {
    state: "Karnataka",
    district: "Chamrajnagar",
    market: "Chamaraj Nagar",
    commodity: "Raddish",
    variety: "Raddish",
    grade: "FAQ",
    arrival_date: "29/10/2024",
    min_price: "1500",
    max_price: "2500",
    modal_price: "2000",
    icon: "\ud83d\udce6",
  },
  {
    state: "Karnataka",
    district: "Davangere",
    market: "Channagiri",
    commodity: "Arecanut(Betelnut/Supari)",
    variety: "Rashi",
    grade: "FAQ",
    arrival_date: "29/10/2024",
    min_price: "44000",
    max_price: "51000",
    modal_price: "48971",
    icon: "\ud83d\udce6",
  },
  {
    state: "Karnataka",
    district: "Dharwad",
    market: "Kalagategi",
    commodity: "Maize",
    variety: "Local",
    grade: "FAQ",
    arrival_date: "29/10/2024",
    min_price: "2050",
    max_price: "2315",
    modal_price: "2210",
    icon: "\ud83c\udf3d",
  },
  {
    state: "Karnataka",
    district: "Hassan",
    market: "Arasikere",
    commodity: "Copra",
    variety: "other",
    grade: "FAQ",
    arrival_date: "29/10/2024",
    min_price: "8000",
    max_price: "8000",
    modal_price: "8000",
    icon: "\ud83d\udce6",
  },
  {
    state: "Karnataka",
    district: "Hassan",
    market: "Arasikere",
    commodity: "Ginger(Green)",
    variety: "Green Ginger",
    grade: "FAQ",
    arrival_date: "29/10/2024",
    min_price: "2800",
    max_price: "2800",
    modal_price: "2800",
    icon: "\ud83c\udf3f",
  },
  {
    state: "Karnataka",
    district: "Kolar",
    market: "Chintamani",
    commodity: "Capsicum",
    variety: "Capsicum",
    grade: "FAQ",
    arrival_date: "29/10/2024",
    min_price: "2000",
    max_price: "3500",
    modal_price: "2500",
    icon: "\ud83c\udf36\ufe0f",
  },
  {
    state: "Karnataka",
    district: "Kolar",
    market: "Chintamani",
    commodity: "Drumstick",
    variety: "Drumstick",
    grade: "FAQ",
    arrival_date: "29/10/2024",
    min_price: "3000",
    max_price: "5000",
    modal_price: "4000",
    icon: "\ud83d\udce6",
  },
];
